measure_steps:
- !MouseAction
  action: &id001 !OperateAction 'CLICK'
  button: &id002 !!python/object/apply:pynput.mouse._win32.Button
  - !!python/tuple
    - 4
    - 2
    - 0
  delay: 0.5319058895111084
  is_checked: true
  list_item_id: 0
  scroll_dx: 0
  scroll_dy: 0
  x_pos: 29
  y_pos: 51
- !MouseAction
  action: *id001
  button: *id002
  delay: 1.5239455699920654
  is_checked: true
  list_item_id: 1
  scroll_dx: 0
  scroll_dy: 0
  x_pos: 45
  y_pos: 66
- !MouseAction
  action: *id001
  button: *id002
  delay: 0.1710832118988037
  is_checked: true
  list_item_id: 2
  scroll_dx: 0
  scroll_dy: 0
  x_pos: 495
  y_pos: 300
- !MouseAction
  action: *id001
  button: *id002
  delay: 0.0
  is_checked: true
  list_item_id: 3
  scroll_dx: 0
  scroll_dy: 0
  x_pos: 495
  y_pos: 300
ui_info:
  loop_count: 1
